{ pkgs, shared, ... }:
let
  ci = pkgs.writeShellApplication {
    name = "ci";

    runtimeInputs = shared.core.nativeBuildInputs ++ shared.core.buildInputs;

    # Ignore the warnings generated by the pre-commit shellHook
    excludeShellChecks = [
      "SC2157"
      "SC2221"
      "SC2222"
      "SC2295"
      "SC2006"
      "SC2086"
    ];

    text = ''
      set -euo pipefail

      export LD_LIBRARY_PATH="${shared.core.env.LD_LIBRARY_PATH}"

      echo "Running pre-commit checks..."
      ${shared.preCommit.shellHook}

      echo "Running cargo tests..."
      cargo test
    '';
  };
in
{
  ci = {
    type = "app";
    program = "${ci}/bin/ci";
  };
}
