[package]
name = "open-game-rules-core"
version = "0.1.0-dev"
edition.workspace = true

[lib]
crate-type = ["cdylib", "lib", "staticlib"]
name = "open_game_rules_core"

[dependencies]
crux_core = { workspace = true, features = ["testing"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[build-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
