FROM nixos/nix:2.35.1@sha256:377d4887aca98f0dfa12971c1ea6d6a625a435d8b610d4c95a436843da6fbfd1
# Enable Nix flakes
RUN echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf

WORKDIR /app

COPY flake.nix flake.lock ./
RUN nix flake archive

COPY nix/ ./nix/
COPY rust-toolchain.toml/ ./
RUN nix develop .#core -c true

COPY . .
RUN --mount=type=cache,target=/app/target \
    --mount=type=cache,target=/root/.cargo/registry \
    echo "Run pre-commit checks" && nix develop .#core -c pre-commit run -a
RUN --mount=type=cache,target=/app/target \
    --mount=type=cache,target=/root/.cargo/registry \
    nix develop .#core -c cargo test
